# swagger link: http://localhost:8080/swagger-ui/index.html
spring:
  main:
    allow-bean-definition-overriding: true
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  cache:
    type: redis  # this enable caching in redis in memory db, none - disabled
    redis:
      time-to-live: PT60M #one hour cache holds
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/offers
      auto-index-creation: true # to have unique id values in db

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

myjoboffers:
      offer:
        http:
          client:
            config:
              connectionTimeout: 1000
              readTimeout: 1000
              uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
              port: 5057

        scheduler:
            request:
               delay: PT3H
#              delay: "*/5 * * * * *"

scheduling:
      enabled: true

auth:
  jwt:
    expirationDays: 30
    secret: ${JWT_SECRET}
    issuer: job-offers-backend