myjoboffers:
  offer:
    scheduler:
      request:
         delay: PT1s
#              delay: "*/5 * * * * *"

scheduling:
  enabled: false

spring:
  cache:
    type: none # disable redis
    redis:
      time-to-live: PT10S